import L from "leaflet";
import "leaflet/dist/leaflet.css";
import { useEffect, useMemo, useRef, useState } from "react";
import concelhosGeo from "@/assets/concelhos.json";
import { heatOpacity, SELECTED_OPACITY } from "@/utils/concelho";
import { type Pin, pinRadius } from "@/utils/pins";
import "./concelho-map.css";

/**
 * The município outlines as Leaflet reads them: GeoJSON, [lng, lat].
 * Generated by `bun run concelhos:build` — see scripts/build-concelhos.ts.
 */
type ConcelhoFeature = {
	type: "Feature";
	properties: { name: string; anchor: [number, number] };
	geometry: { type: "MultiPolygon"; coordinates: number[][][][] };
};

const GEO = concelhosGeo as unknown as { features: ConcelhoFeature[] };

export type ConcelhoMapProps = {
	counts: Map<string, number>;
	/** The busiest concelho in the window: the ramp's ceiling. */
	max: number;
	/** Concelho name, or "" for none. */
	selected: string;
	onSelect: (name: string) => void;
	/** Every place the window can honestly draw, busiest first (Layer 2). */
	pins: Pin[];
	/** The venue slug picked in the filter bar or the list, or "". */
	selectedVenue: string;
	onSelectVenue: (slug: string) => void;
};

type Palette = {
	heat: string;
	line: string;
	ink: string;
	quiet: string;
	/** The page surface: what a pin's ring is cut out of. */
	surface: string;
};

/**
 * The theme lives in CSS custom properties, and the map is the one surface that
 * is not HTML — so read the tokens rather than restate the hex codes here. A
 * probe element resolves `var()` chains for us, which is what makes `.light`
 * (and any future token edit) reach the map for free.
 */
function readToken(token: string, fallback: string): string {
	if (typeof document === "undefined") return fallback;
	const probe = document.createElement("span");
	probe.style.color = `var(${token})`;
	probe.style.position = "absolute";
	probe.style.visibility = "hidden";
	document.body.appendChild(probe);
	const value = getComputedStyle(probe).color.trim();
	probe.remove();
	return value || fallback;
}

function readPalette(): Palette {
	return {
		heat: readToken("--p443-primary", "#ff8c00"),
		line: readToken("--border", "#2a2a2a"),
		ink: readToken("--foreground", "#e5e5e5"),
		quiet: readToken("--muted-foreground", "#a3a3a3"),
		surface: readToken("--background", "#0b0b0b"),
	};
}

/** Recolour when the theme flips (the `.dark` / `.light` class swaps the tokens). */
function usePalette(): Palette {
	const [palette, setPalette] = useState<Palette>(readPalette);
	useEffect(() => {
		const observer = new MutationObserver(() => setPalette(readPalette()));
		const options: MutationObserverInit = {
			attributes: true,
			attributeFilter: ["class"],
		};
		observer.observe(document.documentElement, options);
		observer.observe(document.body, options);
		return () => observer.disconnect();
	}, []);
	return palette;
}

const label = (name: string, count: number) =>
	`<span class="concelho-label__name">${name}</span>` +
	(count > 0 ? `<span class="concelho-label__count">${count}</span>` : "");

/**
 * Leaflet writes tooltip content as HTML, and a venue name is text a scraper
 * copied off a stranger's page. Everything that reaches a tooltip goes through
 * here first — the concelho names happen to be our own, the venue names are
 * not.
 */
function escapeHtml(value: string): string {
	return value
		.replace(/&/g, "&amp;")
		.replace(/</g, "&lt;")
		.replace(/>/g, "&gt;")
		.replace(/"/g, "&quot;");
}

/**
 * A pin's tooltip: what the place is, how much is on there. The count is the
 * pin's own — one place's window — and never a concelho's, which is the number
 * the shading already carries.
 */
function pinLabel(pin: Pin): string {
	const where =
		pin.scope === "lugar" ? `povoação · ${pin.concelho}` : pin.concelho;
	return (
		`<span class="pin-label__name">${escapeHtml(pin.name)}</span>` +
		`<span class="pin-label__meta">${escapeHtml(where)} · ${pin.count} ` +
		`${pin.count === 1 ? "evento" : "eventos"}</span>`
	);
}

/** How many names a map this wide can carry before they pile up. */
function labelBudget(width: number): number {
	if (width >= 900) return 16;
	if (width >= 640) return 10;
	if (width >= 420) return 7;
	return 6;
}

/** Where a label looks when its spot is taken: a small grid, nearest ring first. */
const RINGS = [0, 14, 26, 38];
const NUDGES: [number, number][] = RINGS.flatMap((dx) =>
	RINGS.map((dy) => [dx, dy] as [number, number]),
).sort((a, b) => a[0] * a[0] + a[1] * a[1] - (b[0] * b[0] + b[1] * b[1]));

const overlap = (a: DOMRect, b: DOMRect): boolean =>
	Math.min(a.right, b.right) - Math.max(a.left, b.left) > 4 &&
	Math.min(a.bottom, b.bottom) - Math.max(a.top, b.top) > 4;

/**
 * Labels are the one thing Leaflet will not arrange for us.
 *
 * Sixteen names do not fit on a district drawn inside a phone, so this pass
 * spends a label budget first — the pick always first, then the busiest — and
 * then nudges the survivors apart on a small grid, nearest ring first. A name
 * that still has nowhere to sit is dropped rather than stacked: an unlabelled
 * shape is a gap, two labels on top of each other is a misread number. Nothing
 * is lost to it either way — the ranked list beside the map carries every
 * concelho, and hovering a bare shape brings its label back while the pointer
 * is on it.
 *
 * Returns the names that ended up labelled, which is what the hover handler
 * needs to know before it re-shows one.
 */
function arrangeLabels(
	paths: Map<string, L.Path>,
	counts: Map<string, number>,
	keep: Set<string>,
	selected: string,
): Set<string> {
	const elements = new Map<string, HTMLElement>();
	for (const [name, path] of paths) {
		const element = path.getTooltip()?.getElement();
		if (!element) continue;
		element.style.margin = "0";
		element.style.display = keep.has(name) ? "" : "none";
		elements.set(name, element);
	}

	const order = [...keep].sort((a, b) => {
		if (a === selected) return -1;
		if (b === selected) return 1;
		return (counts.get(b) ?? 0) - (counts.get(a) ?? 0);
	});
	const placed: DOMRect[] = [];
	const settled: string[] = [];
	for (const name of order) {
		const element = elements.get(name);
		if (!element) continue;
		let landed: [number, number] | null = null;
		for (const [dx, dy] of NUDGES) {
			element.style.marginLeft = `${dx}px`;
			element.style.marginTop = `${dy}px`;
			const candidate = element.getBoundingClientRect();
			if (placed.every((taken) => !overlap(candidate, taken))) {
				landed = [dx, dy];
				break;
			}
		}
		if (!landed) {
			// Nowhere free: the name goes, so the number beside it stays readable.
			element.style.display = "none";
			continue;
		}
		element.style.marginLeft = `${landed[0]}px`;
		element.style.marginTop = `${landed[1]}px`;
		placed.push(element.getBoundingClientRect());
		settled.push(name);
	}

	return new Set(settled);
}

/**
 * The district, drawn as nineteen shapes and no basemap.
 *
 * A tile layer would put the whole world on screen to explain one district, and
 * every free tile style fights the brand: this layer answers a single question —
 * how much is on, and where — so the shapes are the map. Leaflet still does the
 * projection, the panning and the hit-testing, which is the part worth having.
 *
 * Layer 2 puts the placed venues on top of the same canvas: a dot per place,
 * sized by its own count. No tiles are wanted for it either — the district's
 * own outlines are the reference, and a vendor basemap would add a key, a bill
 * and a second visual language to a page that already draws the geography it
 * needs.
 *
 * Leaflet's vector paths are not focusable (only its markers are), so the map is
 * a pointer affordance: the ranked lists beside it — concelhos and places — are
 * the same numbers as real buttons, and are the route for keyboard and
 * screen-reader users.
 */
export default function ConcelhoMap({
	counts,
	max,
	selected,
	onSelect,
	pins,
	selectedVenue,
	onSelectVenue,
}: ConcelhoMapProps) {
	const holder = useRef<HTMLDivElement | null>(null);
	const mapRef = useRef<L.Map | null>(null);
	const paths = useRef(new Map<string, L.Path>());
	const labelled = useRef(new Set<string>());
	const arrange = useRef<() => void>(() => {});
	const onSelectRef = useRef(onSelect);
	onSelectRef.current = onSelect;
	const selectedRef = useRef(selected);
	selectedRef.current = selected;
	const onSelectVenueRef = useRef(onSelectVenue);
	onSelectVenueRef.current = onSelectVenue;
	const palette = usePalette();
	const [mounted, setMounted] = useState(false);

	const features = useMemo(
		() => ({ type: "FeatureCollection" as const, features: GEO.features }),
		[],
	);

	// Mount once. Restyling happens in the effect below, on the same instances.
	useEffect(() => {
		const element = holder.current;
		if (!element || mapRef.current) return;

		const map = L.map(element, {
			// The district is the whole canvas: wheel-zoom would hijack the page
			// scroll on the way past, so zoom is buttons and pinch only.
			scrollWheelZoom: false,
			zoomControl: true,
			attributionControl: true,
			zoomSnap: 0.25,
			zoomDelta: 0.5,
			minZoom: 8,
			maxZoom: 14,
			// Fade the shapes in rather than snapping them: the ramp is the content.
			fadeAnimation: !window.matchMedia("(prefers-reduced-motion: reduce)").matches,
		});
		mapRef.current = map;
		// Pins get their own pane above the shapes: `bringToFront()` on a picked
		// concelho reorders within the overlay pane only, so a dot can never end
		// up hidden under the shape it sits in.
		const pinPane = map.createPane("map-pins");
		pinPane.style.zIndex = "460";
		setMounted(true);

		const layer = L.geoJSON(features as never, {
			attribution:
				'Limites © <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',
			style: () => ({ color: "transparent", weight: 0.75, fillColor: "transparent" }),
			onEachFeature: (feature, path) => {
				const { name, anchor } = (feature as ConcelhoFeature).properties;
				paths.current.set(name, path as L.Path);
				(path as L.Path).bindTooltip(label(name, 0), {
					permanent: true,
					direction: "center",
					className: "concelho-label",
					interactive: false,
				});
				// Tooltips are positioned by the polygon's centre, which for a
				// concave concelho can sit outside it — the generated anchor is a
				// point known to be inside, so pin the tooltip there instead.
				(path as L.Path)
					.getTooltip()
					?.setLatLng(L.latLng(anchor[1], anchor[0]));
				path.on("click", () => onSelectRef.current(name));

				// A shape whose name was spent out of the label budget still says
				// what it is when you point at it — and only then.
				path.on("mouseover", () => {
					const shape = paths.current.get(name);
					shape?.setStyle({ weight: 1.75, opacity: 1 });
					const element = shape?.getTooltip()?.getElement();
					if (element && !labelled.current.has(name)) {
						element.style.display = "";
						element.dataset.borrowed = "1";
					}
				});
				path.on("mouseout", () => {
					const shape = paths.current.get(name);
					const picked = selectedRef.current === name;
					shape?.setStyle({ weight: picked ? 2 : 0.75, opacity: picked ? 1 : 0.9 });
					const element = shape?.getTooltip()?.getElement();
					if (element?.dataset.borrowed) {
						element.style.display = "none";
						delete element.dataset.borrowed;
					}
				});
			},
		}).addTo(map);

		const bounds = layer.getBounds();
		map.fitBounds(bounds, { padding: [16, 16] });
		map.setMaxBounds(bounds.pad(0.35));
		// Zoom changes the fit, so the labels are laid out again each time.
		map.on("zoomend", () => arrange.current());
		// The pane is sized by CSS after mount; without this the first paint can
		// land before the box is measured and the district renders off-centre.
		requestAnimationFrame(() => map.invalidateSize());

		return () => {
			map.remove();
			mapRef.current = null;
			paths.current.clear();
		};
	}, [features]);

	/**
	 * Which concelhos get a name on the map right now: the busiest that fit, plus
	 * the pick. Recomputed on paint, on zoom, and never by hiding a number the
	 * page does not carry elsewhere.
	 */
	const paintLabels = () => {
		const width = mapRef.current?.getContainer().clientWidth ?? 0;
		const ranked = [...paths.current.keys()].sort(
			(a, b) => (counts.get(b) ?? 0) - (counts.get(a) ?? 0),
		);
		const keep = new Set(ranked.slice(0, labelBudget(width)));
		if (selected) keep.add(selected);
		labelled.current = arrangeLabels(paths.current, counts, keep, selected);
	};
	arrange.current = paintLabels;

	/**
	 * The pins, redrawn whenever the window or the pick changes.
	 *
	 * A hundred circles is nothing to Leaflet, so there is no diffing here: the
	 * pane is emptied and drawn again. One code path for "these are the pins"
	 * beats an add/update/remove triple that has to agree with itself.
	 */
	useEffect(() => {
		const map = mapRef.current;
		if (!map || !mounted) return;

		const busiest = pins.reduce(
			(top, pin) => (pin.count > top ? pin.count : top),
			0,
		);
		const layer = L.layerGroup();
		const drawn: { slug: string; marker: L.CircleMarker }[] = [];

		// Quiet places first, so the busy ones are the ones that survive an
		// overlap — Leiria city alone holds fourteen of them.
		for (const pin of [...pins].sort((a, b) => a.count - b.count)) {
			const picked = pin.slug === selectedVenue;
			const settlement = pin.scope === "lugar";
			const quiet = settlement ? 0.14 : 0.78;
			const marker = L.circleMarker([pin.lat, pin.lng], {
				pane: "map-pins",
				radius: pinRadius(pin.count, busiest) + (picked ? 2 : 0),
				fillColor: palette.heat,
				fillOpacity: picked ? (settlement ? 0.5 : 1) : quiet,
				// A building is a solid dot cut out of the page; a settlement is
				// a dashed ring, which is all its coordinate claims to be.
				color: picked || settlement ? palette.heat : palette.surface,
				weight: picked ? 2 : settlement ? 1.25 : 1.5,
				dashArray: settlement ? "2 3" : undefined,
				opacity: 1,
			});
			marker.bindTooltip(pinLabel(pin), {
				className: "pin-label",
				direction: "top",
				offset: [0, -2],
			});
			marker.on("click", () => onSelectVenueRef.current(pin.slug));
			marker.on("mouseover", () =>
				marker.setStyle({ fillOpacity: settlement ? 0.4 : 1 }),
			);
			marker.on("mouseout", () =>
				marker.setStyle({
					fillOpacity: picked ? (settlement ? 0.5 : 1) : quiet,
				}),
			);
			if (picked) marker.bringToFront();
			layer.addLayer(marker);
			drawn.push({ slug: pin.slug, marker });
		}

		layer.addTo(map);
		for (const { slug, marker } of drawn) {
			// A name on the DOM element, so a test (or a stylesheet) can find a
			// pin without going through Leaflet's internals.
			(marker.getElement() as Element | undefined)?.setAttribute(
				"data-venue",
				slug,
			);
		}

		return () => {
			layer.remove();
		};
	}, [pins, selectedVenue, palette, mounted]);

	// Paint: heat by count, amber solid for the pick, and each tooltip's number.
	useEffect(() => {
		for (const [name, path] of paths.current) {
			const count = counts.get(name) ?? 0;
			const isSelected = selected === name;
			path.setStyle({
				fillColor: palette.heat,
				fillOpacity: isSelected ? SELECTED_OPACITY : heatOpacity(count, max),
				color: isSelected ? palette.heat : palette.line,
				weight: isSelected ? 2 : 0.75,
				opacity: isSelected ? 1 : 0.9,
			});
			if (isSelected) path.bringToFront();
			path.setTooltipContent(label(name, count));
			// A name on the DOM element, so a test (or a stylesheet) can find a
			// shape without going through Leaflet's internals.
			(path.getElement() as Element | undefined)?.setAttribute("data-concelho", name);
		}

		const container = mapRef.current?.getContainer();
		if (container) {
			container.style.setProperty("--map-line", palette.line);
			container.style.setProperty("--map-ink", palette.ink);
			container.style.setProperty("--map-quiet", palette.quiet);
		}

		// Layout waits a frame: Leaflet only places the tooltips after it has
		// measured the pane, and measuring them before that reads stale boxes.
		const frame = requestAnimationFrame(() => arrange.current());
		return () => cancelAnimationFrame(frame);
	}, [counts, max, selected, palette]);

	return (
		<div
			ref={holder}
			className="concelho-map h-[58svh] min-h-[320px] w-full sm:h-[520px]"
			role="img"
			aria-label="Mapa do distrito de Leiria: eventos por concelho e por local. As listas ao lado têm os mesmos números."
		/>
	);
}
